Decathlon/moon

package-lock.json, package.json, tsconfig.json
TS compiler: use commonjs intead of esnext
=> chore(TS compiler): use commonjs intead of esnext

package-lock.json, package.json, tsconfig.json
=> fix(TS): ts compiler target to es5

package-lock.json, package.json, src/hooks.ts, src/store.ts
=> fix(useQueries): fix use multiple queries

package-lock.json, package.json, src/query-hook.tsx
=> chore(Query): set error to null

package-lock.json, package.json, src/store.ts
set the query before calling the handlers to keep the store updated
=> chore(Store): set the query before calling the handlers

packages/moon-axios/package.json, packages/moon/README.md, packages/moon/package.json
=> chore(readme), update

packages/moon/package.json, packages/moon/src/query-hook.tsx
=> chore(query): remove useeffect

packages/moon-axios/package.json
=> chore(package): fix types path

packages/moon-axios/package.json
=> Fix package

package-lock.json, package.json, packages/moon/package.json
react-query upgrade
♥ Thank you!
=> chore(versions): upgrade react-query

package-lock.json, package.json, packages/moon-graphql/README.md, packages/moon-graphql/jest.config.js, packages/moon-graphql/package.json, packages/moon-graphql/rollup.config.js, packages/moon-graphql/src/index.ts, packages/moon-graphql/test/index.test.tsx, packages/moon-graphql/test/typings/tests-entry.d.ts, packages/moon-graphql/tsconfig.es.json, packages/moon-graphql/tsconfig.json, packages/moon-graphql/tsconfig.test.json, packages/moon-graphql/tsconfig.umd.json
add the moon GraphQL connector
♥ Thank you!
=> feat(graphql): add the moon graphql connector

package-lock.json, package.json, packages/moon/package.json, packages/moon/src/hooks.ts, packages/moon/src/infiniteQuery.tsx, packages/moon/src/query.tsx, packages/moon/src/useInfiniteQuery.tsx, packages/moon/src/useQuery.tsx, packages/moon/test/integration/hooks.test.tsx, packages/moon/test/integration/query-hook.test.tsx, packages/moon/test/integration/query.test.tsx
update react-query version, improve TS types
♥ Thank you!
=> fix: update react-query version, improve TS types

packages/moon/package.json, packages/moon/src/hooks.ts, packages/moon/src/query.tsx
=> chore(hooks): fix useQueryresult-state hooks

packages/moon-graphql/package.json, packages/moon-graphql/src/index.ts, packages/moon/package.json, packages/moon/src/useQuery.tsx
=> chore(useQuery): cancel previous query before refetch

README.md, packages/moon-graphql/README.md, packages/moon-graphql/package.json, packages/moon/README.md, packages/moon/package.json, packages/moon/src/index.ts, packages/moon/src/usePrefetchQuery.tsx, packages/moon/test/integration/hooks.test.tsx
add usePrefetchQuery hook
♥ Thank you!
=> feat(prefetch): add usePrefetchQuery hook

packages/moon-graphql/package.json, packages/moon-graphql/src/index.ts
=> fix(graphqlConnector): throw error

packages/moon-axios/package.json, packages/moon-axios/src/index.ts, packages/moon-graphql/package.json, packages/moon-graphql/src/index.ts, packages/moon/package.json, packages/moon/src/moonClient.tsx, packages/moon/src/utils/client.ts
=> feat(axios): add patch mutation

packages/moon/package.json, packages/moon/src/moonClient.tsx, packages/moon/src/moonProvider.tsx
=> fix(TS): clientFactory is optional

packages/moon-graphql/package.json, packages/moon-graphql/src/index.ts, packages/moon/test/testUtils.ts
fix graphql mutation
♥ Thank you!
=> fix(MoonGraphQL): fix mutation

packages/moon/package.json, packages/moon/src/hooks.ts
update observers if query id changes
♥ Thank you!
=> chore(Observers): update observers if query id changes

package-lock.json, package.json, packages/moon/package.json, packages/moon/src/hooks.ts
=> chore(react-query): upgrade react query version
